project:
  type: website

website:
  page-navigation: true
  title: "AGRS AI Tech Workgrop "
  favicon: favicon.ico
  site-url: "https://junchuanyu.netlify.app/"
  repo-url: ""
  repo-actions: [issue]
  google-analytics: "G-2J79YYG9CZ"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Junchuan Yu. "
    right:
      - icon: envelope
        text: Email
        href: mailto:yujunchuan@mail.cgs.gov.cn
      - icon: github
        text: GitHub
        href: https://github.com/JunchuanYu/AGRS-AI-Tech-Workgroup

  navbar:
    right:
      - text: About
        href: about.qmd
      - text: News
        href: News/index.qmd
      - text: Reports
        href: Reports/index.qmd
      - text: Tutorials
        href: Tutorials/index.qmd
      - icon: github
        href: https://github.com/JunchuanYu/AGRS-AI-Tech-Workgroup
      # - icon: book
      #   href: https://www.zhihu.com/people/yu-jun-chuan-84
      # - icon: bootstrap
      #   href: https://space.bilibili.com/18814004/

format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.junchuanyu\.com\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true

editor: visual

# comments:
#   giscus:
#     repo: JunchuanYu/blog-en
